### ISSUE TITLE
next should be an extra parameter

### ISSUE THREAD

**Issue by ggrossetie** [s-leroux/asciidoctor.js-pug#16]
In my opinion it makes sense because `next` is really an optional feature (and not part of the "template context"). It's also consistent with Express router: https://expressjs.com/en/guide/using-middleware.html

```js
app.use(function (req, res, next) {
  console.log('Time:', Date.now())
  next()
})
```

**before**
```js
const doc = asciidoctor.load('Hello world', {
  templates: [{
    paragraph: (ctx) => {
      if (ctx.node.roles.has('SECRET')) {
        return '<div>CENSORED</div>';
      }
      return ctx.next();
    },
  }],
});
```

**after**
```js
const doc = asciidoctor.load('Hello world', {
  templates: [{
    paragraph: (ctx, next) => {
      if (ctx.node.roles.has('SECRET')) {
        return '<div>CENSORED</div>';
      }
      return next();
    },
  }],
});
```

Another benefit is that the context will only contains an Asciidoctor node and basically a node is really all we need in a "template context" so we could do:

```js
const doc = asciidoctor.load('Hello world', {
  templates: [{
    paragraph: (node, next) => {
      if (node.roles.has('SECRET')) {
        return '<div>CENSORED</div>';
      }
      return next();
    },
  }],
});
```

I think it's better and consistent with Pug templates where the Asciidoctor node is available (without the `ctx.` prefix).

What do you think ?

**Comment by s-leroux** [comment]
Just passing by while working on something else, so I might miss the point.
Does that means we would only have two variable mapped to the template context: `node` and `next`?

Sounds reasonable to me.

**Comment by ggrossetie** [comment]
> Does that means we would only have two variable mapped to the template context: node and next?

Yes.
Does it make sense to map `next` for Pug templates ? If it does, I think we should add an example on how to use it.

**Comment by s-leroux** [comment]
I will look at that this WE (as well as the getAttrbitue thing)

**Comment by ggrossetie** [comment]
:tada:
